aws:
  s3:
    region: ap-northeast-2
    bucketName: catchreview-s3
    access-key: AKIAX3UY4W52DAMLX7XR
    secret-key: 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

# access-key AKIAW27MNKYXX27NJWZX
# secret-key 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
