domain: http://localhost:8080/

spring:
  config:
    activate:
      on-profile: local
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/catchreview
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: true # System.out.println() 으로 로그를 남기기 때문에 밑에 logging 으로 처리
        format_sql: true
        use_sql_comments: false
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: catchreview.io@gmail.com
    password: dwtgcolpmveziimv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.springframework.security: debug
