domain: http://localhost:8080/

spring:
  config:
    activate:
      on-profile: local
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/catchreview
    username: root
    password: 1234
    initialization-mode: never  # data.sql init enabled
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: true # System.out.println() 으로 로그를 남기기 때문에 밑에 logging 으로 처리
        format_sql: true
        use_sql_comments: false
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: groovee.io@gmail.com
    password: dwtgcolpmveziimv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 929231379808-emf2d4kcp4tkorud23cl3v09u7v82k9f.apps.googleusercontent.com
            client-secret: it-lkbBbJqTsnuXvDqrGiwjn
            scope:
              - email
              - profile

          # https://developers.naver.com/docs/login/devguide/devguide.md#3-4-2-%EB%84%A4%EC%95%84%EB%A1%9C-%EC%97%B0%EB%8F%99-url-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0
          naver:
            client-id: R_duunjJWftZ05fSI_C2
            client-secret: RmZsarL1ga
            scope:
              - email
              - nickname
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: 8177d21d8e72b743936d8e7c3a12e758
            client-secret:
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 인증 요청
            token-uri: https://nid.naver.com/oauth2.0/token # Request sAccess Token
            user-info-uri: https://openapi.naver.com/v1/nid/me  # Profile API
            user-name-attribute: response # json key name
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 인증 요청
            token-uri: https://kauth.kakao.com/oauth/token # Request sAccess Token
            user-info-uri: https://kapi.kakao.com/v2/user/me  # Profile API
            user-name-attribute: properties # json key name

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.springframework.security: debug
